sonar.projectKey=ShopNova-Logistics
sonar.projectName=ShopNova-Logistics
sonar.sourceEncoding=UTF-8

sonar.sources=app.py
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py

sonar.python.version=3.12

sonar.exclusions=\
.jenkins-venv/**,\
venv/**,\
.scannerwork/**,\
.pytest_cache/**,\
**/__pycache__/**,\
**/*.pyc,\
templates/**,\
static/**,\
k8s/**
